(function(l,m,A,u){var p=function(){function c(a){if(a&&f.O(a)){var e={name:null,w:null,f:null};if(0<=a.indexOf(".")){a=a.split(".",2);var c=a[0];a=a[1];if(!d[c])return;e.w=c}if(0<=a.indexOf(":")){a=a.split(":",2);c=a[0];a=a[1];if(!b[c])return;e.f=c}if(e.f||y.prototype[a])return e.name=a,e}}var b={},d={},a={create:function(a,b,c){if(!a)return!1;b=b||a;if(d[b])return!1;d[b]=new y(a,b,c);return!0},exec:function(a){var e=Array.prototype.slice.call(arguments,1);if("exec"===a)return!1;if(p[a])return p[a].apply(null,
e);var h=c(a);if(!h)return!1;var k=b[h.f];if(f.isArray(k))return b[h.f].push(Array.prototype.slice.call(arguments,0)),!0;if(k&&!k[h.name])return!1;for(var l=h.w?[d[h.w]]:f.values(d),r=e.length&&f.o(e[-1])?e[-1].callback:u,t=f.H(),m=!0,n=0;n<l.length;n++){var z=l[n];r&&(e[-1].callback=t.B());m=(k||z)[h.name].apply(z,e)&&m}t.complete(r);return m},get:function(a,b){b=b||f.c;"identity"===a&&v.N(n.b(function(a){b(a)}))},register:function(a,d){if(!b[a]||!f.j(d))return!1;var c=b[a];b[a]=d();setTimeout(function(){for(var a=
0;a<c.length;a++)p.exec.apply(null,c[a])});return!0},require:function(a){if(b[a])return!1;b[a]=[];w.fa("/plugins/"+a+".js");return!0},set:function(b,d){a.h=a.h||function(a,b){p.exec("associate",a,{callback:b})};switch(b){case "captureEmailForms":d?x.C(a.h):x.da(a.h)}}};return a}(),x=function(){function c(){h=function(){m.addEventListener("submit",g,!1);setTimeout(function(){m.removeEventListener("submit",g,!1)});return!0};m.addEventListener("submit",h,!0);m.addEventListener("click",a,!0)}function b(a){var b=
/\S+@\S+.\S/;a=a.getElementsByTagName("input");for(var d,g=0;g<a.length;g++)if(d=a[g],!d.hasAttribute("center-ignore")&&(d.hasAttribute("center-associate-email")||"email"===d.type||0<=d.name.toLowerCase().replace(/[^a-z]+/gi,"").indexOf("email")||0<=d.id.toLowerCase().replace(/[^a-z]+/gi,"").indexOf("email")||0<=d.className.toLowerCase().replace(/[^a-z]+/gi,"").indexOf("email")))return b.test(d.value)?d.value:null;return null}function d(a,d){function g(){if(!a.G){a.G=!0;if(d){var b=m.createElement("input");
b.type="hidden";for(var c=["name","value"],e=0;e<c.length;e++){var k=b,f=c[e],h=void 0,h=h||f,f=d.getAttribute(f);null!==f&&k.setAttribute(h,f)}a.appendChild(b);b=["action","enctype","method","novalidate","target"];for(c=0;c<b.length;c++)e=a,h="form"+b[c],k=(k=b[c])||h,h=d.getAttribute(h),null!==h&&e.setAttribute(k,h)}HTMLFormElement.prototype.centerOldSubmit.call(a)}}try{for(var c=b(a),e=f.H(),k=0;k<n.length;k++)n[k].call(null,c,e.B());e.complete(g)}catch(h){g()}setTimeout(g,2E3)}function a(a){var b=
a.target;if(b&&0<="INPUT BUTTON".indexOf(b.tagName)&&0<="submit image button".indexOf(b.type)){a=a.target;b=a;if(b.form)b=b.form;else for(;b&&"FORM"!==b.tagName;)b=b.parentElement;b&&!b.hasAttribute("center-ignore")&&(b.centerActor=a)}}function g(a){if(!1!==a.returnValue&&!a.defaultPrevented){var c=a.target;if(c&&!c.hasAttribute("center-ignore")&&b(c))return d(c,c.centerActor),a.preventDefault(),!1}}function e(){HTMLFormElement.prototype.centerOldSubmit=HTMLFormElement.prototype.submit;HTMLFormElement.prototype.submit=
function(){if(this.hasAttribute("center-ignore")||!b(this))return HTMLFormElement.prototype.centerOldSubmit.call(this);d(this,null)}}var h,k=!1,n=[];return{C:function(a){!k&&m.addEventListener&&l.HTMLFormElement&&!k&&(c(),e(),k=!0);n.push(a)},da:function(b){b=n.indexOf(b);-1<b&&n.splice(b,1);!n.length&&k&&k&&(m.removeEventListener("submit",h,!0),m.removeEventListener("click",a,!0),HTMLFormElement.prototype.submit=void 0,k=!1)}}}(),w=function(){return{F:function(c,b,d){d=d||f.c;var a={method:"GET"};
a.url="https://api.leadpages.io"+c+"?"+f.R(b);var g=new XMLHttpRequest;"withCredentials"in g?(g.open(a.method,a.url,!0),g.withCredentials=!0,g.onreadystatechange=function(){4===g.readyState&&(a.code=g.T,400<=g.status?d(g.responseText,a):d(null,a))},g.ontimeout=function(){a.T=0;d("TIMEOUT",a)},g.send()):(c=new Image,f.D(c,"load",function(){d(null,a)}),c.src=a.url)},fa:function(c){var b=m.createElement("script");b.async=!0;b.src="https://js.center.io"+c;m.getElementsByTagName("head")[0].appendChild(b)}}}(),
n=function(){var c=[],b={flush:function(){if(c.length){for(var b=[],a=[],g=[],e=0;e<c.length;e++)b.push(c[e].kind),a.push(c[e].label),g.push(c[e].value);c.length=0;b={version:"1.8.3",correlateBy:f.K("center-correlate-by")||f.L(),origin:"center-js",kind:b,label:a,value:g};w.F("/analytics/v1/observations/capture",b)}},g:function(d,a,g){c.push({kind:d,label:a,value:g});b.A=b.A||f.U(b.flush,4E3,!1);b.A()},u:function(d,a){if(l.performance&&l.performance.getEntriesByName){var c=performance.getEntriesByName(a)[0];
c&&c.duration&&b.g("timer",d,c.duration)}},ca:function(d){if(!(l.performance&&l.performance.mark&&l.performance.measure&&l.performance.getEntriesByName))return f.c;var a="center-"+d+"-s",c="center-"+d+"-e",e="center-"+d;performance.mark(a);return function(){performance.mark(c);performance.measure(e,a,c);b.u(d,e)}},P:function(d){if(d)try{var a={uid:f.i("centerVisitorId")||"",url:q.M(),ua:navigator.userAgent,n:(d.name||"").substr(0,100),m:(d.message||"").substr(0,100),s:(d.stack||"").replace(/\s+/gi,
" ").substr(0,500)};b.g("text","error",f.R(a));b.flush()}catch(c){}},b:function(d,a){a=a||l;return function(){try{return d.apply(a,arguments)}catch(c){b.P(c)}}},ga:function(d){for(var a in d)d.hasOwnProperty(a)&&f.j(d[a])&&(d[a]=b.b(d[a],d))}};return b}(),q=function(){return{V:function(){return{x:l.innerWidth||(m.documentElement||{}).clientWidth||(m.body||{}).clientWidth||0,y:l.innerHeight||(m.documentElement||{}).clientHeight||(m.body||{}).clientHeight||0}},W:function(){return m.referrer},X:function(c){function b(b){b=
Math.abs(Math.floor(b));return(10>b?"0":"")+b}c=c||new Date;c=-c.getTimezoneOffset();return(0<=c?"+":"-")+b(c/60)+":"+b(c%60)},M:function(){return l.location.toString().replace(/ /g,"%20")},Y:function(){var c=f.J(q.Z());(c=c.utm_email||c.center_email||c.email||c.wemail||u)&&(c=c.replace(/ /g,"+"));return c},Z:function(){return l.location.search||""}}}(),y=function(){function c(a,d,c){var h=this;h.ba=a;h.name=d;h.options=f.I(c||{},b);l.fbq&&m.querySelector&&(a=m.querySelector('meta[name="fb-pixel-id"]'))&&
a.content&&(h.options.facebookPixelId=a.content);!h.options.servingTags&&m.querySelector&&(a=m.querySelector('meta[name="leadpages-serving-tags"]'))&&a.content&&a.content.split&&(h.options.servingTags=a.content.split(","));h.options.captureEmailForms&&x.C(function(a,b){h.associate(a,{callback:b})});h.options.captureEmailURLs&&(a=q.Y())&&h.associate(a)}var b={captureEmailForms:!1,captureEmailURLs:!0,customId:""},d={view:"ViewContent",conversion:"Lead"};c.prototype.associate=function(a,b){b=b||{};b.email=
a;return this.send("association",null,null,null,b)};c.prototype.send=function(a,b,c,h,k){var p=this,r={};r.callback=f.c;r.customId="";k=f.I(k||{},p.options,r);var t=k.callback;k.callback=function(){try{k.facebookPixelId&&d[a]&&l.fbq("track",d[a],{referrer:m.referrer,userAgent:navigator.userAgent,language:navigator.language}),t()}catch(b){t()}};v.N(n.b(function(d){var f=q.V();d={k:a||"",a:b||"",l:c||"",v:h||"",e:k.email||"",st:k.servingTags||"",pid:p.ba,uid:d.uid,sid:d.sid,cid:k.customId,uri:q.M().substr(0,
1E3),rf:q.W().substr(0,500),rx:f.x,ry:f.y,tz:q.X()};w.F("/analytics/v1/events/capture",d,function(b,a){n.u("send-events",a.url);b?(n.P({name:"HTTPError",message:a.method+" "+a.url+" "+a.T,stack:b}),n.flush(),k.callback(!1)):k.callback()})}));return!0};return c}(),f=function(){var c={D:function(b,d,a,c){b.addEventListener?b.addEventListener(d,a,c):b.attachEvent&&b.attachEvent("on"+d,a)},H:function(){return new function(){function b(){e>=c&&d&&!a&&(a=!0,d.call(l))}var d=null,a=!1,c=0,e=0;return{B:function(){c++;
return function(){e++;setTimeout(b)}},complete:function(a){d=a}}}},U:function(b,d,a){function c(){var g=this,k=Array.prototype.slice.call(arguments,0),f=a&&!e;clearTimeout(e);e=setTimeout(function(){e=null;a||b.apply(g,k)},d);f&&b.apply(g,k)}var e;c.clear=function(){clearTimeout(e);e=null};return c},I:function(b){var d=Array.prototype.slice.call(arguments,1);if(!d.length)return b;for(var a=0;a<d.length;a++)for(var c=d[a],e=f.keys(c),h=0;h<e.length;h++){var k=e[h];b[k]===u&&(b[k]=c[k])}return b},J:function(b){if(!f.O(b))return null;
if(!b)return{};var d={};b=b.replace(/(^\?)/,"").split("&");for(var a=0;a<b.length;a++){var c=b[a].split("=");if(c[1]&&0<=c[1].indexOf(","))try{d[decodeURIComponent(c[0])]=decodeURIComponent(c[1]).split(",")}catch(e){}else try{d[decodeURIComponent(c[0])]=decodeURIComponent(c[1])}catch(e){}}return d},forEach:function(b,d,a){if(Array.prototype.forEach)return Array.prototype.forEach.call(b,d,a);for(var c=0;c<b.length;c++)d.call(a,b[c],c,b)},G:function(b){return decodeURIComponent(m.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+
encodeURIComponent(b).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"))||null},K:function(b,d){d=d||l.location.search;var a=(new RegExp("[?&]"+encodeURIComponent(b)+"(=([^&#]*)|&|#|$)")).exec(d);return a?a[2]?decodeURIComponent(a[2].replace(/\+/g," ")):"":null},ha:function(b){try{return localStorage.getItem(b)}catch(d){return null}},i:function(b){try{return sessionStorage.getItem(b)}catch(d){return null}},L:function(){return"xxxxxxxxxxxxxxxxxxxxxx".replace(/[x]/g,function(){return"23456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz".charAt(Math.floor(57*
Math.random()))})},isArray:function(b){return!(!b||!b.constructor||b.constructor!==Array)},j:function(b){return!(!b||"function"!==typeof b)},o:function(b){return!(!b||"object"!==typeof b)},O:function(b){return"string"===typeof b},keys:function(b){if(!f.o(b))return[];var d=[],a;for(a in b)b.hasOwnProperty(a)&&d.push(a);return d},ia:function(b){return Array.prototype.slice.call(b,0)},c:function(){},ea:function(b,d,a,c){b.removeEventListener?b.removeEventListener(d,a,c):b.detachEvent&&b.detachEvent("on"+
d,a)},R:function(b){var d="",a;for(a in b)b.hasOwnProperty(a)&&(d+="&"+encodeURIComponent(a)+"=",d=c.isArray(b[a])?d+encodeURIComponent(b[a]).replace(/%2C/g,","):d+encodeURIComponent(b[a]));return d.substr(1,d.length)},ja:function(b,d,a,c,e){m.cookie=encodeURIComponent(b)+"="+encodeURIComponent(d)+"; expires=Fri, 31 Dec 9999 23:59:59 GMT"+(a?"; domain="+a:"")+(c?"; path="+c:"")+(e?"; secure":"")},ka:function(b,d){try{return localStorage.setItem(b,d)}catch(a){return null}},S:function(b,d){try{return sessionStorage.setItem(b,
d)}catch(a){return null}},values:function(b){if(!f.o(b))return[];var d=[],a;for(a in b)b.hasOwnProperty(a)&&d.push(b[a]);return d}};return c}(),v=function(){function c(){for(var c=0;c<a.length;c++)a[c].call(l,{uid:d,sid:b});a.length=0}var b=null,d=null,a=[],g={$:function(a){var b=n.ca("load-identify"),c=m.createElement("iframe"),d=n.b(function(g){0==="https://js.center.io".indexOf(g.origin||(g.originalEvent||{}).origin)&&(g=f.J(g.data))&&g.s&&g.id&&(b(),f.ea(l,"message",d,!1),c.parentNode&&c.parentNode.removeChild(c),
a(g))});f.D(l,"message",d,!1);c.src="https://js.center.io/identify.html";c.style.display="none";c.style.visibility="hidden";c.style.position="absolute";c.style.left="-9999px";c.style.top="-9999px";m.getElementsByTagName("head")[0].appendChild(c)},aa:function(){b=f.i("centerSessionId");b||(b=f.L(),f.S("centerSessionId",b));(d=f.i("centerVisitorId"))?(n.g("counter","ident-cache","1"),c()):g.$(n.b(function(a){n.g("counter",a.s,"1");d=a.id;f.S("centerVisitorId",d);c()}))},N:function(c){d?c.call(l,{uid:d,
sid:b}):a.push(c)}};return g}();n.ga(p);n.b(function(){if(null===f.K("center-no-load")){var c=l[A]||"center";l[c]=l[c]||f.c;var b=l[c].q||[];l[c]=function(a){return f.j(a)?(a(l[c]),!0):p.exec.apply(p,arguments)};l[c].hash="";l[c].version="1.8.3";l[c].loaded=!0;v.aa();for(var d=0;d<b.length;d++)l[c].apply(l[name],b[d]);n.u("load-center","https://js.center.io/center.js")}})()})(window,document,"LeadPagesCenterObject");
